name: mongodb_docker_app
description: Flutter app with Docker MongoDB
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.10.0
  path_provider: ^2.1.1
  path: ^1.8.3
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  msix: ^3.16.6

flutter:
  uses-material-design: true